baseURL = 'https://abundance-io.github.io'
languageCode = 'en-us'
title = 'abds musings'
theme = 'terminal'
[params]
# dir name of your main content (default is `content/posts`).
# the list of set content will show up on your index page (baseurl).
contentTypeName = "posts"

# ["orange", "blue", "red", "green", "pink"]
themeColor = "pink"

# if you set this to 0, only submenu trigger will be visible
showMenuItems = 5

# show selector to switch language
showLanguageSelector = false

# set theme to full screen width
fullWidthTheme = false

# center theme with default width
centerTheme = true

# if your resource directory contains an image called `cover.(jpg|png|webp)`,
# then the file will be used as a cover automatically.
# With this option you don't have to put the `cover` param in a front-matter.
autoCover = true

# set post to show the last updated
# If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
showLastUpdated = false

# set a custom favicon (default is a `themeColor` square)
# favicon = "favicon.ico"

# Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
# updatedDatePrefix = "Updated"

# set all headings to their default size (depending on browser settings)
# oneHeadingSize = true # default

# whether to show a page's estimated reading time
# readingTime = false # default

# whether to show a table of contents
# can be overridden in a page's front-matter
# Toc = false # default

# set title for the table of contents
# can be overridden in a page's front-matter
# TocTitle = "Table of Contents" # default


[params.twitter]
# set Twitter handles for Twitter cards
# see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
# do not include @
creator = ""
site = ""

[languages]
[languages.en]
languageName = "English"
title = ":)"
subtitle = "musings of the simple minded"
owner = "abundance"
keywords = ""
copyright = ""
menuMore = "See more stuff"
readMore = "Read some more"
readOtherPosts = "Check out my other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
missingContentMessage = "nothing's here lol :)"
missingBackButtonLabel = "Back to the awesome home page"

[languages.en.params.logo]
logoText = "Abd"
logoHomeLink = "/"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about"
[[languages.en.menu.main]]
identifier = "projects"
name = "Projects"
url = "/showcase"

[[languages.en.menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts"

[[languages.en.menu.main]]
identifier = "musings"
name = "Musings"
url = "/musings"
